apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: secret-www-demo
  # Change this to your own domain
  commonName: www.demo.jetstack.net
  dnsNames:
  # Change this to your own domain
  - www.demo.jetstack.net
  issuerRef:
    name: issuer
    kind: Issuer
  acme:
    config:
    - http01:
        ingress: ingress
      domains:
      # Change this to your own domain
      - www.demo.jetstack.net